version: "3.4"

services:
  game:
    build:
      context: .
      target: dev
    working_dir: /game
    restart: on-failure
    volumes:
      - .:/game:z
      - /game/node_modules
    ports:
      - "8100:8100"
